### ISSUE TITLE
👻

### ISSUE THREAD

**Issue by AbhinavMishra32** [shubhgupta15/Login#2]
👻
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
spam promo
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
http://abhinavmishra.in/projects/slots-game.html
heheheheh
http://abhinavmishra.in/projects/slots-game.html

**Comment by shubhgupta15** [comment]
bruh

**Comment by shubhgupta15** [comment]
candy crusher but shit? @AbhinavMishra32

**Comment by AbhinavMishra32** [comment]
🤬😤
